# Generated by Django 4.0.5 on 2022-06-16 13:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='operationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='licenseData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('identifier', models.TextField(blank=True, null=True)),
                ('namespace', models.CharField(max_length=100)),
                ('licenseData', models.TextField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.status')),
            ],
        ),
        migrations.CreateModel(
            name='licenseChangeTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 6, 16, 19, 3, 34, 970911))),
                ('comments', models.TextField(blank=True, null=True)),
                ('licenseId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.licensedata')),
                ('operationType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.operationtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
