# Generated by Django 4.0.5 on 2022-06-21 13:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_alter_licensechangetracking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='licenseTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 6, 21, 19, 25, 16, 107772))),
                ('comments', models.TextField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.licensedata')),
                ('operationType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.operationtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='licenseChangeTracking',
        ),
    ]
