# Generated by Django 4.0.5 on 2022-06-29 17:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_licensetracking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedata',
            name='identifier',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='licensedata',
            name='namespace',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Namespaces can have only alphabets, numbers, underscores and dashes', regex='^[A-Za-z0-9_-]*$')]),
        ),
        migrations.AlterField(
            model_name='licensetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 22, 55, 42, 598374)),
        ),
    ]
