# Generated by Django 4.0.5 on 2022-07-03 10:45

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_licensedata_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='namespace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namespaceText', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='licensedata',
            name='identifier',
            field=models.TextField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Identifier should be a sequence of alphabets / digits / '-' / '.' ", regex='^[A-Za-z0-9.-]*$')]),
        ),
        migrations.AlterField(
            model_name='licensetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 16, 15, 24, 683584)),
        ),
        migrations.AlterField(
            model_name='licensedata',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.namespace'),
        ),
    ]
