# Generated by Django 4.0.5 on 2022-08-17 16:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0019_alter_licensetracking_date_exportheaderfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportheaderfields',
            name='creationInfoCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 22, 2, 1, 98632)),
        ),
        migrations.AlterField(
            model_name='exportheaderfields',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licensetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 22, 2, 1, 97632)),
        ),
    ]
