# Generated by Django 4.0.5 on 2022-06-16 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensechangetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 19, 39, 27, 19393)),
        ),
        migrations.AlterField(
            model_name='licensedata',
            name='namespace',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
