# Generated by Django 4.0.5 on 2022-06-21 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_licensetracking_delete_licensechangetracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 19, 26, 38, 112015)),
        ),
    ]
