# Generated by Django 4.0.5 on 2022-06-29 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_type_licensedata_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedata',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='licensetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 22, 20, 19, 734269)),
        ),
    ]
