# Generated by Django 4.0.5 on 2022-06-29 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_licensedata_name_alter_licensetracking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 22, 22, 7, 361734)),
        ),
    ]
