# Generated by Django 4.0.5 on 2022-07-05 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_licensetracking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 12, 52, 58, 372182)),
        ),
        migrations.AlterModelTable(
            name='licensedata',
            table='License Data',
        ),
        migrations.AlterModelTable(
            name='licensetracking',
            table='License Tracking',
        ),
        migrations.AlterModelTable(
            name='namespace',
            table='Namespace',
        ),
        migrations.AlterModelTable(
            name='operationtype',
            table='Operation Types',
        ),
        migrations.AlterModelTable(
            name='status',
            table='Status',
        ),
    ]
