# Generated by Django 4.0.5 on 2022-07-05 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_licensetracking_date_alter_licensedata_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 21, 25, 23, 148729)),
        ),
    ]
