# Generated by Django 4.0.5 on 2022-09-04 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_exportheaderfields_setheader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedata',
            name='SimplifiedlicenseData',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exportheaderfields',
            name='creationInfoCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 20, 47, 42, 611432)),
        ),
        migrations.AlterField(
            model_name='licensetracking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 20, 47, 42, 611432)),
        ),
    ]
